spring:
  application:
    name: examenes-app
  datasource:
    url: jdbc:mysql://localhost:3306/examenes_app
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true